package com.sweetpotatoclock.entity;

import java.io.Serializable;

public class AchieveList implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achieve_list.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achieve_list.achieve_id
     *
     * @mbg.generated
     */
    private Integer achieveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achieve_list.user_id
     *
     * @return the value of achieve_list.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achieve_list.user_id
     *
     * @param userId the value for achieve_list.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achieve_list.achieve_id
     *
     * @return the value of achieve_list.achieve_id
     *
     * @mbg.generated
     */
    public Integer getAchieveId() {
        return achieveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achieve_list.achieve_id
     *
     * @param achieveId the value for achieve_list.achieve_id
     *
     * @mbg.generated
     */
    public void setAchieveId(Integer achieveId) {
        this.achieveId = achieveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", achieveId=").append(achieveId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}