package com.sweetpotatoclock.entity;

import org.springframework.stereotype.Component;

import java.io.Serializable;
import java.util.Date;

@Component
public class GoalDayComplete implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goal_day_complete.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goal_day_complete.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goal_day_complete.complete_date
     *
     * @mbg.generated
     */
    private Date completeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goal_day_complete
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goal_day_complete.user_id
     *
     * @return the value of goal_day_complete.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goal_day_complete.user_id
     *
     * @param userId the value for goal_day_complete.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goal_day_complete.group_id
     *
     * @return the value of goal_day_complete.group_id
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goal_day_complete.group_id
     *
     * @param groupId the value for goal_day_complete.group_id
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goal_day_complete.complete_date
     *
     * @return the value of goal_day_complete.complete_date
     * @mbg.generated
     */
    public Date getCompleteDate() {
        return completeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goal_day_complete.complete_date
     *
     * @param completeDate the value for goal_day_complete.complete_date
     * @mbg.generated
     */
    public void setCompleteDate(Date completeDate) {
        this.completeDate = completeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goal_day_complete
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", groupId=").append(groupId);
        sb.append(", completeDate=").append(completeDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}