package com.sweetpotatoclock.entity;

import java.io.Serializable;
import java.util.Date;

public class Group implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.captain_id
     *
     * @mbg.generated
     */
    private Integer captainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_name
     *
     * @mbg.generated
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.tag
     *
     * @mbg.generated
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.minutes
     *
     * @mbg.generated
     */
    private Integer minutes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.days
     *
     * @mbg.generated
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.member_number
     *
     * @mbg.generated
     */
    private Integer memberNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.is_private
     *
     * @mbg.generated
     */
    private Byte isPrivate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_id
     *
     * @return the value of group.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_id
     *
     * @param groupId the value for group.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.captain_id
     *
     * @return the value of group.captain_id
     *
     * @mbg.generated
     */
    public Integer getCaptainId() {
        return captainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.captain_id
     *
     * @param captainId the value for group.captain_id
     *
     * @mbg.generated
     */
    public void setCaptainId(Integer captainId) {
        this.captainId = captainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_name
     *
     * @return the value of group.group_name
     *
     * @mbg.generated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_name
     *
     * @param groupName the value for group.group_name
     *
     * @mbg.generated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.tag
     *
     * @return the value of group.tag
     *
     * @mbg.generated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.tag
     *
     * @param tag the value for group.tag
     *
     * @mbg.generated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.minutes
     *
     * @return the value of group.minutes
     *
     * @mbg.generated
     */
    public Integer getMinutes() {
        return minutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.minutes
     *
     * @param minutes the value for group.minutes
     *
     * @mbg.generated
     */
    public void setMinutes(Integer minutes) {
        this.minutes = minutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.days
     *
     * @return the value of group.days
     *
     * @mbg.generated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.days
     *
     * @param days the value for group.days
     *
     * @mbg.generated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.member_number
     *
     * @return the value of group.member_number
     *
     * @mbg.generated
     */
    public Integer getMemberNumber() {
        return memberNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.member_number
     *
     * @param memberNumber the value for group.member_number
     *
     * @mbg.generated
     */
    public void setMemberNumber(Integer memberNumber) {
        this.memberNumber = memberNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.is_private
     *
     * @return the value of group.is_private
     *
     * @mbg.generated
     */
    public Byte getIsPrivate() {
        return isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.is_private
     *
     * @param isPrivate the value for group.is_private
     *
     * @mbg.generated
     */
    public void setIsPrivate(Byte isPrivate) {
        this.isPrivate = isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.create_date
     *
     * @return the value of group.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.create_date
     *
     * @param createDate the value for group.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", captainId=").append(captainId);
        sb.append(", groupName=").append(groupName);
        sb.append(", tag=").append(tag);
        sb.append(", minutes=").append(minutes);
        sb.append(", days=").append(days);
        sb.append(", memberNumber=").append(memberNumber);
        sb.append(", isPrivate=").append(isPrivate);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}