package com.sweetpotatoclock.entity;

import org.springframework.stereotype.Component;

import java.io.Serializable;

@Component
public class MakeTrees implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_trees.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_trees.area
     *
     * @mbg.generated
     */
    private Double area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column make_trees.tree_number
     *
     * @mbg.generated
     */
    private Integer treeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table make_trees
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_trees.user_id
     *
     * @return the value of make_trees.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_trees.user_id
     *
     * @param userId the value for make_trees.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_trees.area
     *
     * @return the value of make_trees.area
     * @mbg.generated
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_trees.area
     *
     * @param area the value for make_trees.area
     * @mbg.generated
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column make_trees.tree_number
     *
     * @return the value of make_trees.tree_number
     * @mbg.generated
     */
    public Integer getTreeNumber() {
        return treeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column make_trees.tree_number
     *
     * @param treeNumber the value for make_trees.tree_number
     * @mbg.generated
     */
    public void setTreeNumber(Integer treeNumber) {
        this.treeNumber = treeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_trees
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", area=").append(area);
        sb.append(", treeNumber=").append(treeNumber);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}