package com.sweetpotatoclock.entity;

import java.io.Serializable;

public class RankInGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_in_group.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_in_group.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_in_group.day_minutes
     *
     * @mbg.generated
     */
    private Integer dayMinutes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_in_group.week_minutes
     *
     * @mbg.generated
     */
    private Integer weekMinutes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rank_in_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_in_group.group_id
     *
     * @return the value of rank_in_group.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_in_group.group_id
     *
     * @param groupId the value for rank_in_group.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_in_group.user_id
     *
     * @return the value of rank_in_group.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_in_group.user_id
     *
     * @param userId the value for rank_in_group.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_in_group.day_minutes
     *
     * @return the value of rank_in_group.day_minutes
     *
     * @mbg.generated
     */
    public Integer getDayMinutes() {
        return dayMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_in_group.day_minutes
     *
     * @param dayMinutes the value for rank_in_group.day_minutes
     *
     * @mbg.generated
     */
    public void setDayMinutes(Integer dayMinutes) {
        this.dayMinutes = dayMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_in_group.week_minutes
     *
     * @return the value of rank_in_group.week_minutes
     *
     * @mbg.generated
     */
    public Integer getWeekMinutes() {
        return weekMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_in_group.week_minutes
     *
     * @param weekMinutes the value for rank_in_group.week_minutes
     *
     * @mbg.generated
     */
    public void setWeekMinutes(Integer weekMinutes) {
        this.weekMinutes = weekMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_in_group
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", userId=").append(userId);
        sb.append(", dayMinutes=").append(dayMinutes);
        sb.append(", weekMinutes=").append(weekMinutes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}