package com.sweetpotatoclock.entity;

import org.springframework.stereotype.Component;

import java.io.Serializable;

@Component
public class RankBetweenGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_between_group.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_between_group.day_average_minutes
     *
     * @mbg.generated
     */
    private Double dayAverageMinutes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank_between_group.week_average_minutes
     *
     * @mbg.generated
     */
    private Double weekAverageMinutes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rank_between_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_between_group.group_id
     *
     * @return the value of rank_between_group.group_id
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_between_group.group_id
     *
     * @param groupId the value for rank_between_group.group_id
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_between_group.day_average_minutes
     *
     * @return the value of rank_between_group.day_average_minutes
     * @mbg.generated
     */
    public Double getDayAverageMinutes() {
        return dayAverageMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_between_group.day_average_minutes
     *
     * @param dayAverageMinutes the value for rank_between_group.day_average_minutes
     * @mbg.generated
     */
    public void setDayAverageMinutes(Double dayAverageMinutes) {
        this.dayAverageMinutes = dayAverageMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank_between_group.week_average_minutes
     *
     * @return the value of rank_between_group.week_average_minutes
     * @mbg.generated
     */
    public Double getWeekAverageMinutes() {
        return weekAverageMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank_between_group.week_average_minutes
     *
     * @param weekAverageMinutes the value for rank_between_group.week_average_minutes
     * @mbg.generated
     */
    public void setWeekAverageMinutes(Double weekAverageMinutes) {
        this.weekAverageMinutes = weekAverageMinutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_between_group
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupId=").append(groupId);
        sb.append(", dayAverageMinutes=").append(dayAverageMinutes);
        sb.append(", weekAverageMinutes=").append(weekAverageMinutes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}