package com.sweetpotatoclock.entity;

import java.io.Serializable;
import java.util.Date;

public class Record implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.minutes
     *
     * @mbg.generated
     */
    private Integer minutes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.user_id
     *
     * @return the value of record.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.user_id
     *
     * @param userId the value for record.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.group_id
     *
     * @return the value of record.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.group_id
     *
     * @param groupId the value for record.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.minutes
     *
     * @return the value of record.minutes
     *
     * @mbg.generated
     */
    public Integer getMinutes() {
        return minutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.minutes
     *
     * @param minutes the value for record.minutes
     *
     * @mbg.generated
     */
    public void setMinutes(Integer minutes) {
        this.minutes = minutes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.date
     *
     * @return the value of record.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.date
     *
     * @param date the value for record.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", groupId=").append(groupId);
        sb.append(", minutes=").append(minutes);
        sb.append(", date=").append(date);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}