package com.sweetpotatoclock.entity;

import org.springframework.stereotype.Component;

import java.io.Serializable;

@Component
public class UserInformation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.user_nickname
     *
     * @mbg.generated
     */
    private String userNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.days_sum
     *
     * @mbg.generated
     */
    private Integer daysSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.minutes_sum
     *
     * @mbg.generated
     */
    private Integer minutesSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_information.continue_days
     *
     * @mbg.generated
     */
    private Integer continueDays;

    private String motto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_information
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public UserInformation() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.user_id
     *
     * @return the value of user_information.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.user_id
     *
     * @param userId the value for user_information.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.user_nickname
     *
     * @return the value of user_information.user_nickname
     * @mbg.generated
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.user_nickname
     *
     * @param userNickname the value for user_information.user_nickname
     * @mbg.generated
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.score
     *
     * @return the value of user_information.score
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.score
     *
     * @param score the value for user_information.score
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.days_sum
     *
     * @return the value of user_information.days_sum
     * @mbg.generated
     */
    public Integer getDaysSum() {
        return daysSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.days_sum
     *
     * @param daysSum the value for user_information.days_sum
     * @mbg.generated
     */
    public void setDaysSum(Integer daysSum) {
        this.daysSum = daysSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.minutes_sum
     *
     * @return the value of user_information.minutes_sum
     * @mbg.generated
     */
    public Integer getMinutesSum() {
        return minutesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.minutes_sum
     *
     * @param minutesSum the value for user_information.minutes_sum
     * @mbg.generated
     */
    public void setMinutesSum(Integer minutesSum) {
        this.minutesSum = minutesSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_information.continue_days
     *
     * @return the value of user_information.continue_days
     * @mbg.generated
     */
    public Integer getContinueDays() {
        return continueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_information.continue_days
     *
     * @param continueDays the value for user_information.continue_days
     * @mbg.generated
     */
    public void setContinueDays(Integer continueDays) {
        this.continueDays = continueDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userNickname=").append(userNickname);
        sb.append(", score=").append(score);
        sb.append(", daysSum=").append(daysSum);
        sb.append(", minutesSum=").append(minutesSum);
        sb.append(", continueDays=").append(continueDays);
        sb.append(", motto=").append(motto);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public void setMotto(String motto) {
        this.motto = motto;
    }
}