package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.AchieveList;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AchieveListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("achieveId") Integer achieveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    int insert(AchieveList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    List<AchieveList> selectAll();
}