package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.AchieveList;
import java.util.List;

public interface AchieveListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    int insert(AchieveList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    List<AchieveList> selectAll();
}