package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.AchieveInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

public interface AchieveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve-info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer achieveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve-info
     *
     * @mbg.generated
     */
    int insert(AchieveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve-info
     *
     * @mbg.generated
     */
    AchieveInfo selectByPrimaryKey(Integer achieveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve-info
     *
     * @mbg.generated
     */
    List<AchieveInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve-info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AchieveInfo record);


}