package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.AchieveList;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface AchieveListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    int insert(AchieveList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achieve_list
     *
     * @mbg.generated
     */
    List<AchieveList> selectAll();

    List<Integer> selectAchieveListByUserId(String userId);
}