package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.GoalComplete;
import java.util.List;

public interface GoalCompleteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goal_complete
     *
     * @mbg.generated
     */
    int insert(GoalComplete record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goal_complete
     *
     * @mbg.generated
     */
    List<GoalComplete> selectAll();
}