package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.Group;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    Group selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    List<Group> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Group record);
}