package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.MakeTrees;
import java.util.List;

public interface MakeTreesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_trees
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_trees
     *
     * @mbg.generated
     */
    int insert(MakeTrees record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_trees
     *
     * @mbg.generated
     */
    MakeTrees selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_trees
     *
     * @mbg.generated
     */
    List<MakeTrees> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table make_trees
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MakeTrees record);
}