package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.RankBetweenGroup;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RankBetweenGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_between_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_between_group
     *
     * @mbg.generated
     */
    int insert(RankBetweenGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_between_group
     *
     * @mbg.generated
     */
    RankBetweenGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_between_group
     *
     * @mbg.generated
     */
    List<RankBetweenGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_between_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RankBetweenGroup record);
}