package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.RankInGroup;
import java.util.List;

public interface RankInGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_in_group
     *
     * @mbg.generated
     */
    int insert(RankInGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank_in_group
     *
     * @mbg.generated
     */
    List<RankInGroup> selectAll();

    void clearDayMinutes();

    void clearWeekMinutes();
}