package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.Record;
import java.util.List;

public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated
     */
    List<Record> selectAll();
}