package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.Record;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface RecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated
     */
    int insert(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated
     */
    List<Record> selectAll();
}