package com.sweetpotatoclock.dao;

import com.sweetpotatoclock.entity.UserInformation;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface UserInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated
     */
    int insert(UserInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated
     */
    UserInformation selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated
     */
    List<UserInformation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInformation record);
}